### ISSUE TITLE
`slic site-cli cli info` version of PHP does not match that of `slic info`

### ISSUE THREAD

**Issue by cliffordp** [stellarwp/slic#147]
`slic site-cli cli info` always shows `PHP version: 7.4.33` but `slic info` shows `SLIC_PHP_VERSION: 8.0`

and it seems `slic composer install` uses the former's version and not the latter's

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1812179/219788624-fb6b1eaf-d334-4479-b6ab-14eeca3eebdf.png">

**Comment by cliffordp** [comment]
@defunctl confirmed _better_ but not sure if 100% _fixed_ because `slic site-cli cli info` gives full version number (`PHP version: 8.0.28`) and `slic info` outputs a truncated/rounded number (`SLIC_PHP_VERSION: 8.0`)

**Comment by defunctl** [comment]
That's correct, the environment variable, `SLIC_PHP_VERSION` is to tell [Slic which PHP minor version should be used](https://github.com/stellarwp/slic/blob/main/src/commands/php-version.php#L28), and `slic site-cli cli info` is just running [wp cli info](https://developer.wordpress.org/cli/commands/cli/info/) inside the container.

These will never match (and aren't meant to), because one is showing you the currently set configuration option for Slic, and the other is the output of a 3rd party dependency/command.

**Comment by cliffordp** [comment]
tyvm good sir
